- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install package for python
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - python3-pip