---
# tasks file for php

- name: Add nginx stable repository from PPA and install its signing key on Ubuntu target
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php

- name: Install PHP-FPM of Ubuntu 20.04
  apt: name={{ item }} update_cache=yes state=latest
  loop: 
    - php8.1
    - php8.1-fpm
    - php8.1-cli
    - php8.1-pdo
    - php8.1-mysql
    - php8.1-zip
    - php8.1-gd
    - php8.1-mbstring
    - php8.1-curl
    - php8.1-xml
    - php-pear
    - php8.1-bcmath

- name: Setup php-fpm
  replace: dest=/etc/php/8.1/fpm/php.ini regexp="(;cgi.fix_pathinfo=1)" replace="cgi.fix_pathinfo=0"
  notify:
    - restart nginx
  become: yes

- name: Add php settings
  template: src=../../nginx/templates/nginx-wp-common.conf dest=/etc/nginx/nginx-wp-common.conf owner=www-data group=www-data mode=0644
  notify:
    - restart nginx
  become: yes
